name: home_widget_example
description: Demonstrates how to use the home_widget plugin.

publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  home_widget: ^0.1.6
  workmanager:
    git:
      url: https://github.com/sunalwaysknows/flutter_workmanager
      ref: f37742bcf612c51e9571d623138a21a90a5992ea

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter: null
